# .github/workflows/build-push.yml
name: Build and Push Lib

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'test/*'
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.0.2'

      - name: Install deps and build
        run: |
          npm ci
          npm run build  # builds lib/

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./lib
